<?php
return [
    'es' => [
        'name' => 'Español',
        'flag' => 'icons/flags/es.svg',
        'login' => 'Entrar',
        'user' => 'Usuario',
        'pass' => 'Contraseña',
        'logout' => 'Cerrar sesión',
        'account_data' => 'Datos de la cuenta',
        'characters' => 'Personajes de la cuenta',
        'email' => 'Correo',
        'register_date' => 'Fecha de registro',
        'last_ip' => 'Última IP',
        'map' => 'Mapa',
        'zone' => 'Zona',
        'played' => 'Tiempo jugado',
        'last_logout' => 'Última desconexión',
        'online' => 'En línea',
        'offline' => 'Desconectado',
        'unstuck' => 'Unstuck',
        'search_email' => 'Buscar cuentas por email',
        'search' => 'Buscar',
        'results' => 'Resultados de la búsqueda',
        'no_results' => 'No se encontraron cuentas con ese email',
        'other_accounts' => 'Otras cuentas con este email'
    ],
    'en' => [
        'name' => 'English',
        'flag' => 'icons/flags/us.svg',
        'login' => 'Login',
        'user' => 'Username',
        'pass' => 'Password',
        'logout' => 'Logout',
        'account_data' => 'Account data',
        'characters' => 'Account characters',
        'email' => 'Email',
        'register_date' => 'Registration date',
        'last_ip' => 'Last IP',
        'map' => 'Map',
        'zone' => 'Zone',
        'played' => 'Played time',
        'last_logout' => 'Last logout',
        'online' => 'Online',
        'offline' => 'Offline',
        'unstuck' => 'Unstuck',
        'search_email' => 'Search accounts by email',
        'search' => 'Search',
        'results' => 'Search results',
        'no_results' => 'No accounts found with that email',
        'other_accounts' => 'Other accounts with this email'
    ]
];

